### ISSUE TITLE
negative interaction with Asana on Firefox

### ISSUE THREAD

**Issue by drjasonharrison** [f-fusco/font-contrast#15]
When I create an issue in [Asana](https://app.asana.com) and paste an image into the description, scrolling the issue vertically crashes Asana.

I didn't have Asana whitelisted or blacklisted, just this font-contrast extension enabled.

**Comment by Fushko** [comment]
Hello, thanks for the report.

I can't reproduce this bug unfortunately. I created an issue, pasted a couple images, put some text and scrolled back and forth, but I'm not getting any crashes. I'm able to turn the extension on and off without issues.

I did use Asana a while ago. I remember adding an optimization that fixed a hang on Asana specifically. Are you on the most recent version of Firefox and Font Contrast?

**Comment by drjasonharrison** [comment]
Almost immediately after creating this issue I found that the asana crash requires an up and down scroll of a particular speed. Would Firefox console logs help?

If asana is neither whitelisted nor blacklisted would Font Contrast have modified the html and css?

Yes latest versions of Firefox and Font Contrast on Ubuntu 18.04 LTS

**Comment by Fushko** [comment]
> Would Firefox console logs help?

If you get any errors when this bug occurs, yes.

> If asana is neither whitelisted nor blacklisted would Font Contrast have modified the html and css?

No, unless you have enabled it manually on that particular tab.
