### ISSUE TITLE
Extension darkens graphics in an undesired fashion..

### ISSUE THREAD

**Issue by Ted-Egan** [f-fusco/font-contrast#16]
With no apparent toggle to say cut it out.

Extension in supposed to darken text.  Don't know why it should be darkening graphic images to the point of unviewability.  Not something any user would want, I imagine.   In any case, would be useful to have a setting option to not have the extension do anything at all to graphics images.  Just want the text made more readable.

**Comment by Fushko** [comment]
Hello, in which website does this happen?
