### ISSUE TITLE
Neither whitelist or blacklist prevents Font Contrast from activating

### ISSUE THREAD

**Issue by jcbeck37** [f-fusco/font-contrast#7]
Steps to reproduce:
1. Add a url to Whitelist (or Blacklist)
2. Visit the url

Expected behavior:
1. Font Contrast does not activate on this domain

Actual Behavior:
1. Font Contrast activates on this domain and has to be manually turned off

**Comment by Fushko** [comment]
Only the subdomain + domain is currently supported for the whitelist/blacklist. What does your url look like?

**Comment by jcbeck37** [comment]
I was able to resolve this - I believe you have to exclude the protocol (https://) for it to work. Though it doesn't give you any feedback or indication that this is blocking the feature from working.

**Comment by Fushko** [comment]
It gives you an example though, which doesn't include the protocol. I'll add some validation/feedback in the future.
